DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS customer;

CREATE TABLE customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(100)
);

CREATE TABLE event (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    scheduled_at TIMESTAMP,
    price DECIMAL(10, 2)
);

CREATE TABLE booking (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT,
    event_id INT,
    booking_date TIMESTAMP,
    booking_number VARCHAR(50),
    status VARCHAR(20),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE ticket (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT,
    FOREIGN KEY (booking_id) REFERENCES booking(id)
);
